# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-10-06 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0004_group_finnished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='finnished',
            field=models.BooleanField(default=False),
        ),
    ]
