# Generated by Django 3.1.2 on 2020-10-13 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0006_auto_20201006_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='time',
        ),
    ]
