# Generated by Django 3.1.2 on 2020-10-20 20:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetables', '0007_remove_shift_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Text',
            new_name='Message',
        ),
    ]
