# Generated by Django 3.1.2 on 2020-10-28 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0008_auto_20201020_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftstatus',
            options={'verbose_name_plural': 'Shift statuses'},
        ),
    ]
