# Generated by Django 3.1.2 on 2020-11-21 23:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetables', '0009_auto_20201028_1234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Absent',
            new_name='DayAbsent',
        ),
    ]
