# Generated by Django 3.1.2 on 2020-11-23 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0010_auto_20201122_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayabsent',
            old_name='day_class',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='dayabsent',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetables.day'),
        ),
    ]
