# Generated by Django 3.1.2 on 2020-12-05 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0012_remove_dayabsent_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='day',
            new_name='date',
        ),
    ]
