# Generated by Django 3.1.2 on 2020-10-27 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timetables', '0008_auto_20201020_2254'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turnus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('group', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='timetables.group')),
            ],
        ),
        migrations.CreateModel(
            name='TurnusShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_class', models.CharField(blank=True, choices=[('y', 'yes'), ('m', 'maybe'), ('n', 'no')], max_length=1, null='True')),
                ('start', models.TimeField(blank=True, null=True)),
                ('end', models.TimeField(blank=True, null=True)),
                ('day', models.CharField(max_length=30)),
                ('employee', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('turnus', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.turnus')),
            ],
        ),
    ]
