# Generated by Django 3.1.2 on 2020-10-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnusshift',
            name='day',
            field=models.CharField(choices=[('Mon', 'ponedeljek'), ('Tue', 'torek'), ('Wed', 'sreda'), ('Thu', 'četrtek'), ('Fri', 'petek'), ('Sat', 'sobota'), ('Sun', 'nedelja')], max_length=30),
        ),
    ]
