# Generated by Django 3.1.2 on 2020-10-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20201028_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnusshift',
            name='day',
            field=models.CharField(blank=True, choices=[('Mon', 'ponedeljek'), ('Tue', 'torek'), ('Wed', 'sreda'), ('Thu', 'četrtek'), ('Fri', 'petek'), ('Sat', 'sobota'), ('Sun', 'nedelja')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='turnusshift',
            name='shift_class',
            field=models.CharField(blank=True, choices=[('y', 'yes'), ('m', 'maybe'), ('n', 'no')], max_length=1, null=True),
        ),
    ]
