# Generated by Django 3.1.2 on 2020-10-28 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_auto_20201028_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turnus',
            options={'verbose_name_plural': 'Turnuses'},
        ),
        migrations.RemoveField(
            model_name='turnusshift',
            name='day',
        ),
        migrations.RemoveField(
            model_name='turnusshift',
            name='shift_class',
        ),
    ]
