# Generated by Django 3.1.2 on 2020-10-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_auto_20201028_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnusshift',
            name='day',
            field=models.CharField(blank=True, choices=[('m', 'maybe'), ('n', 'no')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='turnusshift',
            name='shift_class',
            field=models.CharField(blank=True, choices=[('y', 'yes'), ('m', 'maybe'), ('n', 'no')], max_length=1, null=True),
        ),
    ]
