# Generated by Django 3.1.2 on 2020-10-28 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_auto_20201028_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnusshift',
            name='turnus',
        ),
        migrations.CreateModel(
            name='TurnusDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, choices=[('Mon', 'ponedeljek'), ('Tue', 'torek'), ('Wed', 'sreda'), ('Thu', 'četrtek'), ('Fri', 'petek'), ('Sat', 'sobota'), ('Sun', 'nedelja')], max_length=30, null=True)),
                ('turnus', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.turnus')),
            ],
        ),
        migrations.AlterField(
            model_name='turnusshift',
            name='day',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='administrator.turnusday'),
        ),
    ]
