# Generated by Django 3.1.2 on 2020-11-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_auto_20201028_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnusshift',
            name='day',
            field=models.CharField(blank=True, choices=[('Mon', 'ponedeljek'), ('Tue', 'torek'), ('Wed', 'sreda'), ('Thu', 'četrtek'), ('Fri', 'petek'), ('Sat', 'sobota'), ('Sun', 'nedelja')], max_length=3, null=True),
        ),
        migrations.DeleteModel(
            name='TurnusDay',
        ),
    ]
