# Generated by Django 3.1.2 on 2020-11-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_turnusshift_turnus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnusshift',
            name='day',
            field=models.CharField(blank=True, choices=[('Mon', 'Pon'), ('Tue', 'Tor'), ('Wed', 'Sre'), ('Thu', 'Čet'), ('Fri', 'Pet'), ('Sat', 'Sob'), ('Sun', 'Ned')], max_length=3, null=True),
        ),
    ]
