# Generated by Django 3.1.2 on 2020-12-10 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_auto_20201122_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnusshift',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='turnusshift',
            name='turnus',
        ),
        migrations.DeleteModel(
            name='Turnus',
        ),
        migrations.DeleteModel(
            name='TurnusShift',
        ),
    ]
